FROM golang:1.20-alpine AS deps

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

FROM deps AS build

COPY . .

RUN go build -o build/sidecar ./sidecar

FROM alpine:latest AS runner

COPY --from=build /app/build/sidecar /usr/bin/

ENTRYPOINT ["/usr/bin/sidecar"]
