home: ""
mitosis:
  host: 127.0.0.1
  port: 26657
  wallet-port: 9090
  denom: umito
  prefix: mito
  validator-prefix: mitovaloper
  chain-id: ""
  priv-key: ""
tofn:
  host: 127.0.0.1
  port: 50051
  dial-timeout: 15000000000
  validator: "validator-addr"
  nodes:
    - validator: ""
      host: ""
    - validator: ""
      host: ""
