// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mitosis/multisig/v1beta1/exported/types.proto

package exported

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Sign Status
type Sign_Status int32

const (
	// Unspecified Status
	Sign_StatusUnspeicified Sign_Status = 0
	// Sign event Assigned ( Not executed )
	Sign_StatusAssign Sign_Status = 1
	// Sign event executed
	Sign_StatusExecute Sign_Status = 2
	// Sign event Completed
	Sign_StatusComplete Sign_Status = 3
	// Sign event Success
	Sign_StatusSuccess Sign_Status = 4
	// Sign event Failed
	Sign_StatusFailed Sign_Status = 5
)

var Sign_Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_ASSIGN",
	2: "STATUS_EXECUTE",
	3: "STATUS_COMPLETE",
	4: "STATUS_SUCCESS",
	5: "STATUS_FAILED",
}

var Sign_Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_ASSIGN":      1,
	"STATUS_EXECUTE":     2,
	"STATUS_COMPLETE":    3,
	"STATUS_SUCCESS":     4,
	"STATUS_FAILED":      5,
}

func (x Sign_Status) String() string {
	return proto.EnumName(Sign_Status_name, int32(x))
}

func (Sign_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_678ce0504116f33b, []int{0, 0}
}

// Sign Message
type Sign struct {
	// sign target chain id
	Chain string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	// signature id
	SigID uint64 `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
	// try-to-sign key id
	KeyID string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// participant_ids
	Participants []github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,4,rep,name=participants,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"participants,omitempty"`
	// Message to sign
	MessageToSign Hash        `protobuf:"bytes,5,opt,name=message_to_sign,json=messageToSign,proto3,casttype=Hash" json:"message_to_sign,omitempty"`
	Status        Sign_Status `protobuf:"varint,6,opt,name=status,proto3,enum=manythings.mitosis.v1beta1.multisig.exported.Sign_Status" json:"status,omitempty"`
}

func (m *Sign) Reset()         { *m = Sign{} }
func (m *Sign) String() string { return proto.CompactTextString(m) }
func (*Sign) ProtoMessage()    {}
func (*Sign) Descriptor() ([]byte, []int) {
	return fileDescriptor_678ce0504116f33b, []int{0}
}
func (m *Sign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sign.Merge(m, src)
}
func (m *Sign) XXX_Size() int {
	return m.Size()
}
func (m *Sign) XXX_DiscardUnknown() {
	xxx_messageInfo_Sign.DiscardUnknown(m)
}

var xxx_messageInfo_Sign proto.InternalMessageInfo

func (m *Sign) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *Sign) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

func (m *Sign) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *Sign) GetParticipants() []github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *Sign) GetMessageToSign() Hash {
	if m != nil {
		return m.MessageToSign
	}
	return nil
}

func (m *Sign) GetStatus() Sign_Status {
	if m != nil {
		return m.Status
	}
	return Sign_StatusUnspeicified
}

// SignSignature Message
type SignResult struct {
	Chain string             `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	SigID uint64             `protobuf:"varint,2,opt,name=sig_id,json=sigId,proto3" json:"sig_id,omitempty"`
	Items []*SignResult_Item `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (m *SignResult) Reset()         { *m = SignResult{} }
func (m *SignResult) String() string { return proto.CompactTextString(m) }
func (*SignResult) ProtoMessage()    {}
func (*SignResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_678ce0504116f33b, []int{1}
}
func (m *SignResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResult.Merge(m, src)
}
func (m *SignResult) XXX_Size() int {
	return m.Size()
}
func (m *SignResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResult.DiscardUnknown(m)
}

var xxx_messageInfo_SignResult proto.InternalMessageInfo

func (m *SignResult) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *SignResult) GetSigID() uint64 {
	if m != nil {
		return m.SigID
	}
	return 0
}

func (m *SignResult) GetItems() []*SignResult_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// SignSignature result message
type SignResult_Item struct {
	Participant github_com_cosmos_cosmos_sdk_types.ValAddress `protobuf:"bytes,1,opt,name=participant,proto3,casttype=github.com/cosmos/cosmos-sdk/types.ValAddress" json:"participant,omitempty"`
	Signature   Signature                                     `protobuf:"bytes,2,opt,name=signature,proto3,casttype=Signature" json:"signature,omitempty"`
}

func (m *SignResult_Item) Reset()         { *m = SignResult_Item{} }
func (m *SignResult_Item) String() string { return proto.CompactTextString(m) }
func (*SignResult_Item) ProtoMessage()    {}
func (*SignResult_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_678ce0504116f33b, []int{1, 0}
}
func (m *SignResult_Item) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignResult_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignResult_Item.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignResult_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResult_Item.Merge(m, src)
}
func (m *SignResult_Item) XXX_Size() int {
	return m.Size()
}
func (m *SignResult_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResult_Item.DiscardUnknown(m)
}

var xxx_messageInfo_SignResult_Item proto.InternalMessageInfo

func (m *SignResult_Item) GetParticipant() github_com_cosmos_cosmos_sdk_types.ValAddress {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *SignResult_Item) GetSignature() Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("manythings.mitosis.v1beta1.multisig.exported.Sign_Status", Sign_Status_name, Sign_Status_value)
	proto.RegisterType((*Sign)(nil), "manythings.mitosis.v1beta1.multisig.exported.Sign")
	proto.RegisterType((*SignResult)(nil), "manythings.mitosis.v1beta1.multisig.exported.SignResult")
	proto.RegisterType((*SignResult_Item)(nil), "manythings.mitosis.v1beta1.multisig.exported.SignResult.Item")
}

func init() {
	proto.RegisterFile("mitosis/multisig/v1beta1/exported/types.proto", fileDescriptor_678ce0504116f33b)
}

var fileDescriptor_678ce0504116f33b = []byte{
	// 615 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6e, 0xd3, 0x4c,
	0x18, 0x87, 0xe3, 0xc6, 0x89, 0xbe, 0x4c, 0x93, 0xd6, 0xdf, 0xa8, 0x42, 0x51, 0x16, 0x89, 0x55,
	0x84, 0x88, 0x04, 0xb1, 0x69, 0x59, 0xb1, 0x60, 0x91, 0xa4, 0x2e, 0x58, 0x94, 0x52, 0x3c, 0x31,
	0x42, 0x6c, 0x22, 0xd7, 0x1e, 0x9c, 0x51, 0x63, 0x8f, 0x95, 0x77, 0x8c, 0x9a, 0x1b, 0xa0, 0xac,
	0xb8, 0x40, 0x76, 0x1c, 0x82, 0x23, 0xb0, 0xec, 0x92, 0x55, 0x84, 0xd2, 0x53, 0xd0, 0x15, 0xf2,
	0x9f, 0xa8, 0x66, 0xd9, 0xae, 0xec, 0x19, 0x3f, 0xef, 0xa3, 0xf7, 0x37, 0x33, 0x1e, 0xd4, 0x0b,
	0x98, 0xe0, 0xc0, 0x40, 0x0f, 0xe2, 0xa9, 0x60, 0xc0, 0x7c, 0xfd, 0xcb, 0xc1, 0x39, 0x15, 0xce,
	0x81, 0x4e, 0x2f, 0x23, 0x3e, 0x13, 0xd4, 0xd3, 0xc5, 0x3c, 0xa2, 0xa0, 0x45, 0x33, 0x2e, 0x38,
	0x7e, 0x1a, 0x38, 0xe1, 0x5c, 0x4c, 0x58, 0xe8, 0x83, 0x96, 0x57, 0x6a, 0x79, 0x81, 0xb6, 0x31,
	0x68, 0x9b, 0xca, 0xd6, 0x9e, 0xcf, 0x7d, 0x9e, 0x16, 0xea, 0xc9, 0x5b, 0xe6, 0xd8, 0xff, 0x21,
	0x23, 0x99, 0x30, 0x3f, 0xc4, 0x7b, 0xa8, 0xe2, 0x4e, 0x1c, 0x16, 0x36, 0x25, 0x55, 0xea, 0xd6,
	0xac, 0x6c, 0x80, 0x55, 0x54, 0x05, 0xe6, 0x8f, 0x99, 0xd7, 0xdc, 0x52, 0xa5, 0xae, 0x3c, 0xa8,
	0xad, 0x57, 0x9d, 0x0a, 0x61, 0xbe, 0x79, 0x64, 0x55, 0x80, 0xf9, 0xa6, 0x97, 0x10, 0x17, 0x74,
	0x9e, 0x10, 0xe5, 0xa4, 0x30, 0x23, 0xde, 0xd0, 0x79, 0x42, 0x5c, 0xd0, 0xb9, 0xe9, 0x61, 0x1b,
	0xd5, 0x23, 0x67, 0x26, 0x98, 0xcb, 0x22, 0x27, 0x14, 0xd0, 0x94, 0xd5, 0x72, 0xb7, 0x36, 0x38,
	0xb8, 0x59, 0x75, 0x7a, 0x3e, 0x13, 0x93, 0xf8, 0x5c, 0x73, 0x79, 0xa0, 0xbb, 0x1c, 0x02, 0x0e,
	0xf9, 0xa3, 0x07, 0xde, 0x45, 0x1e, 0xf5, 0x83, 0x33, 0xed, 0x7b, 0xde, 0x8c, 0x02, 0x58, 0xff,
	0x68, 0xf0, 0x33, 0xb4, 0x1b, 0x50, 0x00, 0xc7, 0xa7, 0x63, 0xc1, 0xc7, 0xc0, 0xfc, 0xb0, 0x59,
	0x51, 0xa5, 0x6e, 0x7d, 0xf0, 0xdf, 0xcd, 0xaa, 0x23, 0xbf, 0x76, 0x60, 0x62, 0x35, 0x72, 0x60,
	0xc4, 0xd3, 0x88, 0xef, 0x51, 0x15, 0x84, 0x23, 0x62, 0x68, 0x56, 0x55, 0xa9, 0xbb, 0x73, 0xf8,
	0x42, 0xbb, 0xcb, 0x02, 0x6a, 0x89, 0x43, 0x23, 0xa9, 0xc0, 0xca, 0x45, 0xfb, 0x7f, 0x24, 0x54,
	0xcd, 0xa6, 0xb0, 0x86, 0x30, 0x19, 0xf5, 0x47, 0x36, 0x19, 0xdb, 0xa7, 0xe4, 0xcc, 0x18, 0x9a,
	0xc7, 0xa6, 0x71, 0xa4, 0x94, 0x5a, 0x0f, 0x16, 0x4b, 0x15, 0x67, 0x8c, 0x1d, 0x42, 0x44, 0x99,
	0xcb, 0x3e, 0x33, 0xea, 0xe1, 0x87, 0xa8, 0x91, 0xf3, 0x7d, 0x42, 0xcc, 0x57, 0xa7, 0x8a, 0xd4,
	0x52, 0x16, 0x4b, 0xb5, 0x9e, 0xa1, 0x7d, 0x48, 0x12, 0xe1, 0x47, 0x68, 0x27, 0x87, 0x8c, 0x8f,
	0xc6, 0xd0, 0x1e, 0x19, 0xca, 0x56, 0xeb, 0xff, 0xc5, 0x52, 0x6d, 0x64, 0x94, 0x71, 0x49, 0xdd,
	0x58, 0x50, 0xfc, 0x18, 0xed, 0xe6, 0xd8, 0xf0, 0xdd, 0xdb, 0xb3, 0x13, 0x63, 0x64, 0x28, 0xe5,
	0x16, 0x5e, 0x2c, 0xd5, 0x9d, 0x8c, 0x1b, 0xf2, 0x20, 0x9a, 0x52, 0x41, 0x0b, 0x3e, 0x62, 0x0f,
	0x87, 0x06, 0x21, 0x8a, 0x5c, 0xf4, 0x91, 0xd8, 0x75, 0x29, 0x40, 0xa1, 0xb7, 0xe3, 0xbe, 0x79,
	0x62, 0x1c, 0x29, 0x95, 0x62, 0x6f, 0xc7, 0x0e, 0x9b, 0x52, 0x6f, 0xff, 0xfb, 0x16, 0x42, 0xc9,
	0x9a, 0x58, 0x14, 0xe2, 0xa9, 0xb8, 0xf7, 0x01, 0x22, 0xa8, 0xc2, 0x04, 0x0d, 0xa0, 0x59, 0x56,
	0xcb, 0xdd, 0xed, 0xc3, 0x97, 0x77, 0xdf, 0x94, 0xac, 0x01, 0xcd, 0x14, 0x34, 0xb0, 0x32, 0x57,
	0xeb, 0xab, 0x84, 0xe4, 0x64, 0x8c, 0x09, 0xda, 0x2e, 0x9c, 0x9a, 0xb4, 0xb7, 0xfa, 0x7d, 0xce,
	0x5e, 0xd1, 0x82, 0x9f, 0xa0, 0x5a, 0xb2, 0x3b, 0x8e, 0x88, 0x67, 0x34, 0xcd, 0x55, 0x1f, 0x34,
	0x6e, 0x56, 0x9d, 0x1a, 0xd9, 0x4c, 0x5a, 0xb7, 0xdf, 0x07, 0x27, 0x3f, 0xd7, 0x6d, 0xe9, 0x6a,
	0xdd, 0x96, 0x7e, 0xaf, 0xdb, 0xd2, 0xb7, 0xeb, 0x76, 0xe9, 0xea, 0xba, 0x5d, 0xfa, 0x75, 0xdd,
	0x2e, 0x7d, 0x3a, 0x2c, 0xb4, 0x90, 0x84, 0xee, 0x65, 0xa9, 0xf5, 0xcd, 0x2d, 0x70, 0x79, 0x7b,
	0x0f, 0x6c, 0xf2, 0x9e, 0x57, 0xd3, 0xdf, 0xf6, 0xf9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c,
	0xd9, 0xa1, 0x81, 0x2b, 0x04, 0x00, 0x00,
}

func (m *Sign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.MessageToSign) > 0 {
		i -= len(m.MessageToSign)
		copy(dAtA[i:], m.MessageToSign)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MessageToSign)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Participants[iNdEx])
			copy(dAtA[i:], m.Participants[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Participants[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.KeyID) > 0 {
		i -= len(m.KeyID)
		copy(dAtA[i:], m.KeyID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.KeyID)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SigID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.SigID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SigID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SignResult_Item) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignResult_Item) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignResult_Item) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Participant) > 0 {
		i -= len(m.Participant)
		copy(dAtA[i:], m.Participant)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Participant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovTypes(uint64(m.SigID))
	}
	l = len(m.KeyID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Participants) > 0 {
		for _, s := range m.Participants {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.MessageToSign)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	return n
}

func (m *SignResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.SigID != 0 {
		n += 1 + sovTypes(uint64(m.SigID))
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *SignResult_Item) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Participant)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, github_com_cosmos_cosmos_sdk_types.ValAddress(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageToSign", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageToSign = append(m.MessageToSign[:0], dAtA[iNdEx:postIndex]...)
			if m.MessageToSign == nil {
				m.MessageToSign = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Sign_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigID", wireType)
			}
			m.SigID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &SignResult_Item{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignResult_Item) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Item: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Item: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participant = append(m.Participant[:0], dAtA[iNdEx:postIndex]...)
			if m.Participant == nil {
				m.Participant = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
