// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mitosis/multisig/v1beta1/server/server.proto

package server

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/many-things/mitosis/x/multisig/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("mitosis/multisig/v1beta1/server/server.proto", fileDescriptor_39308092bd06c3d7)
}

var fileDescriptor_39308092bd06c3d7 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0x4f, 0x4f, 0xd4, 0x40,
	0x1c, 0x86, 0x19, 0x51, 0xa2, 0xa3, 0xc4, 0x64, 0xe2, 0xa9, 0x31, 0x3d, 0x18, 0x25, 0xc8, 0x9f,
	0x0e, 0x0b, 0x12, 0x14, 0x03, 0x28, 0x26, 0x1c, 0x44, 0x12, 0x84, 0x9b, 0x17, 0x32, 0x85, 0xc9,
	0x30, 0x81, 0x76, 0x4a, 0x67, 0x4a, 0x6c, 0x36, 0x5c, 0xbc, 0x9b, 0x90, 0x78, 0xf2, 0x63, 0x78,
	0x52, 0x6f, 0x9a, 0x78, 0xf0, 0x42, 0x42, 0xe2, 0x41, 0x8f, 0x66, 0xd7, 0x0f, 0x62, 0x3a, 0xd3,
	0x9d, 0xdd, 0x80, 0x8b, 0xdb, 0xd9, 0x13, 0x0d, 0xed, 0xf3, 0xf2, 0xbc, 0x33, 0xbf, 0x69, 0x81,
	0x13, 0x11, 0x57, 0x42, 0x72, 0x89, 0xa3, 0x6c, 0x5f, 0x71, 0xc9, 0x19, 0x3e, 0xac, 0x85, 0x54,
	0x91, 0x1a, 0x96, 0x34, 0x3d, 0xa4, 0x69, 0xf9, 0x23, 0x48, 0x52, 0xa1, 0x04, 0x1a, 0x8b, 0x48,
	0x9c, 0xab, 0x5d, 0x1e, 0x33, 0x19, 0x94, 0x60, 0x50, 0x3e, 0x1f, 0xb4, 0x02, 0x02, 0x43, 0x78,
	0x63, 0xdb, 0x42, 0x46, 0x42, 0xe2, 0x90, 0x48, 0x8a, 0x0f, 0x32, 0x9a, 0xe6, 0x36, 0x3a, 0x21,
	0x8c, 0xc7, 0x44, 0x71, 0x11, 0x9b, 0x5c, 0xef, 0x16, 0x13, 0x4c, 0xe8, 0x4b, 0x5c, 0x5c, 0x95,
	0xbf, 0xbd, 0xcd, 0x84, 0x60, 0xfb, 0x14, 0x93, 0x84, 0x63, 0x12, 0xc7, 0x42, 0x69, 0x44, 0x96,
	0x77, 0xef, 0x75, 0x35, 0x4f, 0x48, 0x4a, 0xa2, 0xd6, 0x63, 0xf8, 0x7f, 0x05, 0x55, 0x9e, 0x50,
	0xb9, 0x15, 0x49, 0x56, 0x02, 0xb5, 0xde, 0x00, 0xdd, 0xc8, 0x20, 0xd3, 0xdf, 0x06, 0xe1, 0xe0,
	0x9a, 0x64, 0xe8, 0x2d, 0x80, 0xd7, 0x37, 0x15, 0x49, 0xd5, 0x2a, 0xcd, 0x19, 0x8d, 0xd1, 0x7c,
	0xd0, 0xfb, 0x7a, 0x05, 0x6b, 0x92, 0x75, 0xb0, 0xde, 0xb2, 0x3b, 0xbb, 0x41, 0x65, 0x22, 0x62,
	0x49, 0xd1, 0x31, 0x80, 0x37, 0x36, 0xb3, 0x30, 0xe2, 0x6a, 0x3d, 0x0b, 0xf7, 0x68, 0x8e, 0x1e,
	0x57, 0x0d, 0xed, 0x80, 0xbd, 0x67, 0x7d, 0xc0, 0x56, 0xe9, 0x3d, 0x80, 0x37, 0xcd, 0x8d, 0x4d,
	0xce, 0x62, 0xa2, 0xb2, 0x94, 0xa2, 0x45, 0xa7, 0x60, 0xcb, 0x7b, 0x2b, 0xfd, 0xf1, 0x2d, 0xb7,
	0xe9, 0x9f, 0xc3, 0xf0, 0xca, 0xcb, 0x62, 0x5b, 0xd1, 0x47, 0x00, 0x87, 0xd6, 0xf5, 0x14, 0x55,
	0x93, 0xd3, 0xb4, 0x01, 0x37, 0xe8, 0x41, 0x46, 0xa5, 0xf2, 0x96, 0x9c, 0x79, 0x63, 0x75, 0x67,
	0xe2, 0xcd, 0x8f, 0x3f, 0xef, 0x2e, 0x8d, 0xa0, 0xbb, 0xb8, 0x08, 0x9a, 0x34, 0x49, 0xe7, 0xa7,
	0xda, 0x0c, 0x3d, 0xfa, 0x0c, 0xe0, 0x50, 0x39, 0x7d, 0x73, 0x95, 0xff, 0x72, 0x39, 0x7a, 0x4b,
	0x8e, 0xa0, 0x55, 0x9e, 0xd5, 0xca, 0x18, 0x4d, 0x76, 0x3f, 0x7c, 0x7b, 0x9a, 0xc0, 0xf5, 0xed,
	0x5d, 0xc2, 0xe3, 0x23, 0x5c, 0xe7, 0x3b, 0x47, 0xe8, 0x0b, 0x80, 0xd0, 0x24, 0xbd, 0xe0, 0x52,
	0x55, 0x1b, 0xd6, 0x0e, 0x8d, 0x02, 0xae, 0x36, 0xac, 0x67, 0x60, 0xdb, 0x63, 0x4a, 0xf7, 0x18,
	0x43, 0xa3, 0xbd, 0xf6, 0x40, 0x5f, 0x8b, 0xc1, 0xc9, 0xc2, 0x55, 0x9a, 0x3b, 0x2c, 0xbf, 0x01,
	0x5d, 0x26, 0x46, 0x83, 0x56, 0x7b, 0x41, 0x6b, 0xcf, 0xa1, 0xd9, 0xee, 0xda, 0x89, 0x3e, 0x95,
	0xb8, 0xbe, 0x47, 0xf3, 0x2d, 0xbe, 0x73, 0x84, 0xeb, 0x87, 0x64, 0x9f, 0xef, 0x10, 0x25, 0x52,
	0xdd, 0x01, 0x9a, 0x44, 0xc7, 0x6d, 0x68, 0xc3, 0x0e, 0xdb, 0xd0, 0x86, 0x6d, 0x9f, 0x9a, 0xee,
	0x33, 0x8e, 0xee, 0xf7, 0xdc, 0x07, 0x7d, 0x00, 0xf0, 0x72, 0x71, 0xc0, 0xd1, 0x6c, 0x65, 0x81,
	0x02, 0xf3, 0x16, 0x9c, 0x30, 0x6b, 0x3c, 0xa3, 0x8d, 0x27, 0xd1, 0xf8, 0x05, 0x5f, 0x1f, 0xce,
	0xce, 0x8c, 0xff, 0x27, 0x00, 0xaf, 0x16, 0x29, 0x7a, 0xd5, 0x1f, 0x39, 0x09, 0xe8, 0x35, 0x7f,
	0xea, 0x8c, 0x5a, 0xff, 0x40, 0xfb, 0x8f, 0xa2, 0x91, 0xde, 0xfc, 0xd1, 0x09, 0x80, 0xd7, 0xda,
	0xef, 0xf3, 0x79, 0x27, 0x01, 0xf3, 0x2e, 0x5f, 0x76, 0x67, 0xad, 0xfd, 0x13, 0x6d, 0x3f, 0x8f,
	0x1e, 0x5e, 0x6c, 0xaf, 0x21, 0x5c, 0x97, 0x9c, 0x9d, 0x3b, 0x02, 0x27, 0x00, 0x0e, 0xdb, 0x5c,
	0xbd, 0x1f, 0x8b, 0xee, 0x5e, 0x7a, 0x53, 0x56, 0xfa, 0xe3, 0x6d, 0xb7, 0x07, 0xba, 0x5b, 0x80,
	0x26, 0xaa, 0x74, 0x5b, 0x7e, 0xfe, 0xbd, 0xe1, 0x83, 0xd3, 0x86, 0x0f, 0x7e, 0x37, 0x7c, 0x70,
	0xdc, 0xf4, 0x07, 0x4e, 0x9b, 0xfe, 0xc0, 0xaf, 0xa6, 0x3f, 0xf0, 0x6a, 0x8a, 0x71, 0xb5, 0x9b,
	0x85, 0xc1, 0xb6, 0x88, 0xfe, 0xf9, 0x7d, 0x79, 0xdd, 0xce, 0x37, 0x72, 0xe1, 0x90, 0xfe, 0x9f,
	0x67, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xa1, 0xa8, 0xf2, 0x3a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	StartKeygen(ctx context.Context, in *MsgStartKeygen, opts ...grpc.CallOption) (*MsgStartKeygenResponse, error)
	SubmitPubkey(ctx context.Context, in *MsgSubmitPubkey, opts ...grpc.CallOption) (*MsgSubmitPubkeyResponse, error)
	SubmitSignature(ctx context.Context, in *MsgSubmitSignature, opts ...grpc.CallOption) (*MsgSubmitSignatureResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) StartKeygen(ctx context.Context, in *MsgStartKeygen, opts ...grpc.CallOption) (*MsgStartKeygenResponse, error) {
	out := new(MsgStartKeygenResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Msg/StartKeygen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitPubkey(ctx context.Context, in *MsgSubmitPubkey, opts ...grpc.CallOption) (*MsgSubmitPubkeyResponse, error) {
	out := new(MsgSubmitPubkeyResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Msg/SubmitPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitSignature(ctx context.Context, in *MsgSubmitSignature, opts ...grpc.CallOption) (*MsgSubmitSignatureResponse, error) {
	out := new(MsgSubmitSignatureResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Msg/SubmitSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	StartKeygen(context.Context, *MsgStartKeygen) (*MsgStartKeygenResponse, error)
	SubmitPubkey(context.Context, *MsgSubmitPubkey) (*MsgSubmitPubkeyResponse, error)
	SubmitSignature(context.Context, *MsgSubmitSignature) (*MsgSubmitSignatureResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) StartKeygen(ctx context.Context, req *MsgStartKeygen) (*MsgStartKeygenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartKeygen not implemented")
}
func (*UnimplementedMsgServer) SubmitPubkey(ctx context.Context, req *MsgSubmitPubkey) (*MsgSubmitPubkeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPubkey not implemented")
}
func (*UnimplementedMsgServer) SubmitSignature(ctx context.Context, req *MsgSubmitSignature) (*MsgSubmitSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSignature not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_StartKeygen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgStartKeygen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).StartKeygen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Msg/StartKeygen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).StartKeygen(ctx, req.(*MsgStartKeygen))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPubkey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Msg/SubmitPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPubkey(ctx, req.(*MsgSubmitPubkey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitSignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Msg/SubmitSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitSignature(ctx, req.(*MsgSubmitSignature))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manythings.mitosis.v1beta1.multisig.server.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartKeygen",
			Handler:    _Msg_StartKeygen_Handler,
		},
		{
			MethodName: "SubmitPubkey",
			Handler:    _Msg_SubmitPubkey_Handler,
		},
		{
			MethodName: "SubmitSignature",
			Handler:    _Msg_SubmitSignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mitosis/multisig/v1beta1/server/server.proto",
}

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Keygen query
	Keygen(ctx context.Context, in *QueryKeygen, opts ...grpc.CallOption) (*QueryKeygenResponse, error)
	// Keygen list query
	KeygenList(ctx context.Context, in *QueryKeygenList, opts ...grpc.CallOption) (*QueryKeygenListResponse, error)
	// specific pubkey query
	PubKey(ctx context.Context, in *QueryPubKey, opts ...grpc.CallOption) (*QueryPubKeyResponse, error)
	// list pubkey query
	PubKeyList(ctx context.Context, in *QueryPubKeyList, opts ...grpc.CallOption) (*QueryPubKeyListResponse, error)
	// specific sign query
	Sign(ctx context.Context, in *QuerySign, opts ...grpc.CallOption) (*QuerySignResponse, error)
	// list sign query
	SignList(ctx context.Context, in *QuerySignList, opts ...grpc.CallOption) (*QuerySignListResponse, error)
	// specific signature query
	Signature(ctx context.Context, in *QuerySignature, opts ...grpc.CallOption) (*QuerySignatureResponse, error)
	// list signature query
	SignatureList(ctx context.Context, in *QuerySignatureList, opts ...grpc.CallOption) (*QuerySignatureListResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Keygen(ctx context.Context, in *QueryKeygen, opts ...grpc.CallOption) (*QueryKeygenResponse, error) {
	out := new(QueryKeygenResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/Keygen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KeygenList(ctx context.Context, in *QueryKeygenList, opts ...grpc.CallOption) (*QueryKeygenListResponse, error) {
	out := new(QueryKeygenListResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/KeygenList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PubKey(ctx context.Context, in *QueryPubKey, opts ...grpc.CallOption) (*QueryPubKeyResponse, error) {
	out := new(QueryPubKeyResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/PubKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PubKeyList(ctx context.Context, in *QueryPubKeyList, opts ...grpc.CallOption) (*QueryPubKeyListResponse, error) {
	out := new(QueryPubKeyListResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/PubKeyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Sign(ctx context.Context, in *QuerySign, opts ...grpc.CallOption) (*QuerySignResponse, error) {
	out := new(QuerySignResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SignList(ctx context.Context, in *QuerySignList, opts ...grpc.CallOption) (*QuerySignListResponse, error) {
	out := new(QuerySignListResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/SignList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Signature(ctx context.Context, in *QuerySignature, opts ...grpc.CallOption) (*QuerySignatureResponse, error) {
	out := new(QuerySignatureResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/Signature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SignatureList(ctx context.Context, in *QuerySignatureList, opts ...grpc.CallOption) (*QuerySignatureListResponse, error) {
	out := new(QuerySignatureListResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.multisig.server.Query/SignatureList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Keygen query
	Keygen(context.Context, *QueryKeygen) (*QueryKeygenResponse, error)
	// Keygen list query
	KeygenList(context.Context, *QueryKeygenList) (*QueryKeygenListResponse, error)
	// specific pubkey query
	PubKey(context.Context, *QueryPubKey) (*QueryPubKeyResponse, error)
	// list pubkey query
	PubKeyList(context.Context, *QueryPubKeyList) (*QueryPubKeyListResponse, error)
	// specific sign query
	Sign(context.Context, *QuerySign) (*QuerySignResponse, error)
	// list sign query
	SignList(context.Context, *QuerySignList) (*QuerySignListResponse, error)
	// specific signature query
	Signature(context.Context, *QuerySignature) (*QuerySignatureResponse, error)
	// list signature query
	SignatureList(context.Context, *QuerySignatureList) (*QuerySignatureListResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Keygen(ctx context.Context, req *QueryKeygen) (*QueryKeygenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keygen not implemented")
}
func (*UnimplementedQueryServer) KeygenList(ctx context.Context, req *QueryKeygenList) (*QueryKeygenListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeygenList not implemented")
}
func (*UnimplementedQueryServer) PubKey(ctx context.Context, req *QueryPubKey) (*QueryPubKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubKey not implemented")
}
func (*UnimplementedQueryServer) PubKeyList(ctx context.Context, req *QueryPubKeyList) (*QueryPubKeyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PubKeyList not implemented")
}
func (*UnimplementedQueryServer) Sign(ctx context.Context, req *QuerySign) (*QuerySignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedQueryServer) SignList(ctx context.Context, req *QuerySignList) (*QuerySignListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignList not implemented")
}
func (*UnimplementedQueryServer) Signature(ctx context.Context, req *QuerySignature) (*QuerySignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signature not implemented")
}
func (*UnimplementedQueryServer) SignatureList(ctx context.Context, req *QuerySignatureList) (*QuerySignatureListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignatureList not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Keygen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKeygen)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Keygen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/Keygen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Keygen(ctx, req.(*QueryKeygen))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KeygenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKeygenList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KeygenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/KeygenList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KeygenList(ctx, req.(*QueryKeygenList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPubKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/PubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PubKey(ctx, req.(*QueryPubKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PubKeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPubKeyList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PubKeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/PubKeyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PubKeyList(ctx, req.(*QueryPubKeyList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Sign(ctx, req.(*QuerySign))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SignList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SignList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/SignList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SignList(ctx, req.(*QuerySignList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Signature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignature)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Signature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/Signature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Signature(ctx, req.(*QuerySignature))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SignatureList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignatureList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SignatureList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.multisig.server.Query/SignatureList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SignatureList(ctx, req.(*QuerySignatureList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manythings.mitosis.v1beta1.multisig.server.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Keygen",
			Handler:    _Query_Keygen_Handler,
		},
		{
			MethodName: "KeygenList",
			Handler:    _Query_KeygenList_Handler,
		},
		{
			MethodName: "PubKey",
			Handler:    _Query_PubKey_Handler,
		},
		{
			MethodName: "PubKeyList",
			Handler:    _Query_PubKeyList_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Query_Sign_Handler,
		},
		{
			MethodName: "SignList",
			Handler:    _Query_SignList_Handler,
		},
		{
			MethodName: "Signature",
			Handler:    _Query_Signature_Handler,
		},
		{
			MethodName: "SignatureList",
			Handler:    _Query_SignatureList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mitosis/multisig/v1beta1/server/server.proto",
}
