// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mitosis/event/v1beta1/server/server.proto

package server

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("mitosis/event/v1beta1/server/server.proto", fileDescriptor_8493cefcc4fba2c7)
}

var fileDescriptor_8493cefcc4fba2c7 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0x87, 0xbb, 0x6a, 0x23, 0x8e, 0x8a, 0x30, 0xc7, 0x45, 0x57, 0x11, 0xad, 0x7f, 0x68, 0x76,
	0x6c, 0x5a, 0xab, 0x36, 0x55, 0xb0, 0x41, 0x3c, 0x15, 0x62, 0x45, 0x0f, 0x5e, 0xca, 0x24, 0x1d,
	0x36, 0x03, 0xbb, 0x3b, 0x71, 0x66, 0x12, 0x1a, 0x62, 0x2e, 0xc5, 0xab, 0x20, 0xf4, 0x23, 0x78,
	0x50, 0xf0, 0x73, 0x08, 0x1e, 0x3c, 0x14, 0xbc, 0x78, 0x94, 0xc4, 0x2f, 0xe1, 0x4d, 0x66, 0x66,
	0x33, 0x5a, 0xa9, 0x61, 0x67, 0x3c, 0x85, 0xc0, 0xfb, 0xfc, 0xe6, 0x99, 0x97, 0x77, 0xde, 0x04,
	0xdc, 0xc8, 0xa8, 0x64, 0x82, 0x0a, 0x44, 0xfa, 0x24, 0x97, 0xa8, 0xbf, 0xd4, 0x22, 0x12, 0x2f,
	0x21, 0x41, 0x78, 0x9f, 0xf0, 0xe2, 0x23, 0xee, 0x72, 0x26, 0x19, 0xbc, 0x96, 0xe1, 0x7c, 0x20,
	0x3b, 0x34, 0x4f, 0x44, 0x5c, 0x50, 0x71, 0x51, 0x1f, 0x6b, 0x3a, 0x36, 0xe5, 0xe1, 0xf9, 0x84,
	0xb1, 0x24, 0x25, 0x08, 0x77, 0x29, 0xc2, 0x79, 0xce, 0x24, 0x96, 0x94, 0xe5, 0xc2, 0xc4, 0x84,
	0x8b, 0x33, 0x4f, 0x94, 0x83, 0x2e, 0x11, 0xdb, 0x99, 0x48, 0x8a, 0xea, 0xb8, 0x44, 0xf5, 0xcb,
	0x1e, 0xe1, 0x03, 0x53, 0x5f, 0xfb, 0x54, 0x01, 0xc7, 0x37, 0x45, 0x02, 0xf7, 0x02, 0x70, 0xfa,
	0x69, 0xaf, 0x95, 0x51, 0xf9, 0x48, 0x81, 0xf0, 0x4e, 0x5c, 0xd2, 0x3e, 0xde, 0x14, 0xc9, 0x1f,
	0x60, 0xb8, 0xe6, 0x0e, 0x6e, 0x11, 0xd1, 0x65, 0xb9, 0x20, 0xf0, 0x15, 0x38, 0xf5, 0x9c, 0x49,
	0x62, 0x0c, 0x6e, 0xbb, 0x04, 0x59, 0x2c, 0xbc, 0xeb, 0x8a, 0xd9, 0xd3, 0xdf, 0x04, 0xe0, 0xec,
	0x16, 0x49, 0xa8, 0x90, 0x84, 0x37, 0x39, 0xdb, 0x1d, 0xc0, 0x7b, 0x2e, 0x59, 0x87, 0xd0, 0xf0,
	0xa1, 0x37, 0x6a, 0x7d, 0x5e, 0x07, 0x00, 0x34, 0x52, 0x82, 0x0b, 0x99, 0x55, 0x97, 0xc4, 0xdf,
	0x5c, 0xf8, 0xc0, 0x8f, 0x3b, 0xb2, 0x2d, 0x8d, 0x0e, 0xa6, 0xb9, 0x5f, 0x5b, 0x34, 0xea, 0xd7,
	0x16, 0x8d, 0x5a, 0x9f, 0xfd, 0x00, 0x9c, 0x7b, 0x96, 0xf3, 0x43, 0x46, 0x75, 0x97, 0xd8, 0xbf,
	0xe0, 0xb0, 0xf1, 0x1f, 0xf0, 0xd4, 0xaa, 0xf6, 0x13, 0x80, 0xf9, 0x27, 0xea, 0x5d, 0xc1, 0x77,
	0x01, 0xa8, 0x34, 0x31, 0xc7, 0x99, 0x80, 0x2b, 0xa5, 0x93, 0x35, 0x6a, 0xa8, 0x70, 0xdd, 0x87,
	0x9a, 0x8a, 0x5c, 0xbe, 0xba, 0xf7, 0xf5, 0xc7, 0xfe, 0xb1, 0x8b, 0xf0, 0x02, 0x3a, 0x7a, 0x13,
	0x74, 0x8d, 0xda, 0x87, 0x00, 0x9c, 0x68, 0xb2, 0x34, 0x85, 0x35, 0xc7, 0xd3, 0x58, 0x9a, 0x3a,
	0xbc, 0x71, 0xcb, 0x58, 0xbf, 0x5b, 0xda, 0xef, 0x26, 0xbc, 0xfe, 0x2f, 0x3f, 0x96, 0xa6, 0x68,
	0xd8, 0x56, 0xcd, 0x1d, 0xa1, 0x21, 0xdd, 0x19, 0xc1, 0xf7, 0x01, 0x98, 0x57, 0x11, 0x02, 0x2e,
	0xbb, 0x9f, 0x2b, 0xc2, 0xba, 0x07, 0x64, 0x6d, 0x17, 0xb5, 0xed, 0x02, 0xbc, 0x32, 0xc3, 0x56,
	0x4c, 0x75, 0xe1, 0x47, 0x65, 0xaa, 0x1f, 0xab, 0xab, 0xa9, 0x7e, 0xa9, 0x75, 0x0f, 0xa8, 0x7c,
	0x5f, 0x55, 0x35, 0x1a, 0xf6, 0x71, 0x4a, 0x77, 0xb0, 0x64, 0x7c, 0x04, 0xbf, 0x04, 0xe0, 0x4c,
	0x91, 0xd1, 0x27, 0x5c, 0x10, 0xb8, 0xe6, 0x75, 0xbe, 0x66, 0xc3, 0x0d, 0x7f, 0xd6, 0x5e, 0x61,
	0x5d, 0x5f, 0x61, 0x15, 0xae, 0xcc, 0xba, 0x42, 0x95, 0x1b, 0x0a, 0x0d, 0xf5, 0xd7, 0x6d, 0xdc,
	0x6e, 0xb3, 0x5e, 0x2e, 0xf5, 0x98, 0x9c, 0x54, 0xb1, 0x94, 0x08, 0x87, 0xdf, 0x0e, 0x6b, 0x43,
	0x89, 0x08, 0xef, 0x7b, 0x61, 0xd6, 0x7f, 0x41, 0xfb, 0x5f, 0x82, 0xd1, 0x0c, 0x7f, 0x65, 0xa7,
	0x06, 0xda, 0xec, 0x2d, 0xc7, 0x31, 0x31, 0xfb, 0xaa, 0xee, 0x01, 0x95, 0x1e, 0x68, 0x3d, 0xc9,
	0x76, 0xa0, 0xd5, 0x2e, 0xd3, 0xbc, 0xf3, 0x2e, 0x33, 0x94, 0xeb, 0x2e, 0x33, 0x54, 0xe9, 0x5d,
	0xa6, 0x2d, 0xc5, 0xc6, 0xe3, 0xcf, 0xe3, 0x28, 0x38, 0x18, 0x47, 0xc1, 0xf7, 0x71, 0x14, 0xbc,
	0x9d, 0x44, 0x73, 0x07, 0x93, 0x68, 0xee, 0xdb, 0x24, 0x9a, 0x7b, 0x51, 0x4d, 0xa8, 0xec, 0xf4,
	0x5a, 0x71, 0x9b, 0x65, 0x48, 0x89, 0x54, 0x8d, 0x89, 0x8d, 0xdb, 0x2d, 0x02, 0x8d, 0x43, 0xab,
	0xa2, 0xff, 0x13, 0x2d, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x22, 0xe0, 0x9c, 0x43, 0xe5, 0x09,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Submits / Initiates vote for external event.
	SubmitEvent(ctx context.Context, in *MsgSubmitEvent, opts ...grpc.CallOption) (*MsgSubmitResponse, error)
	// Votes to submitted external event.
	VoteEvent(ctx context.Context, in *MsgVoteEvent, opts ...grpc.CallOption) (*MsgVoteResponse, error)
	// Registers an address of proxy account to submit / vote external event rather than execute with validator account itself.
	RegisterProxy(ctx context.Context, in *MsgRegisterProxy, opts ...grpc.CallOption) (*MsgRegisterProxyResponse, error)
	// Clears proxy account info from a validator
	ClearProxy(ctx context.Context, in *MsgClearProxy, opts ...grpc.CallOption) (*MsgClearProxyResponse, error)
	// Register chain info
	RegisterChain(ctx context.Context, in *MsgRegisterChain, opts ...grpc.CallOption) (*MsgRegisterChainResponse, error)
	// Unregister chain info
	UnregisterChain(ctx context.Context, in *MsgUnregisterChain, opts ...grpc.CallOption) (*MsgUnregisterChainResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitEvent(ctx context.Context, in *MsgSubmitEvent, opts ...grpc.CallOption) (*MsgSubmitResponse, error) {
	out := new(MsgSubmitResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/SubmitEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) VoteEvent(ctx context.Context, in *MsgVoteEvent, opts ...grpc.CallOption) (*MsgVoteResponse, error) {
	out := new(MsgVoteResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/VoteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterProxy(ctx context.Context, in *MsgRegisterProxy, opts ...grpc.CallOption) (*MsgRegisterProxyResponse, error) {
	out := new(MsgRegisterProxyResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/RegisterProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClearProxy(ctx context.Context, in *MsgClearProxy, opts ...grpc.CallOption) (*MsgClearProxyResponse, error) {
	out := new(MsgClearProxyResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/ClearProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterChain(ctx context.Context, in *MsgRegisterChain, opts ...grpc.CallOption) (*MsgRegisterChainResponse, error) {
	out := new(MsgRegisterChainResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/RegisterChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterChain(ctx context.Context, in *MsgUnregisterChain, opts ...grpc.CallOption) (*MsgUnregisterChainResponse, error) {
	out := new(MsgUnregisterChainResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Msg/UnregisterChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Submits / Initiates vote for external event.
	SubmitEvent(context.Context, *MsgSubmitEvent) (*MsgSubmitResponse, error)
	// Votes to submitted external event.
	VoteEvent(context.Context, *MsgVoteEvent) (*MsgVoteResponse, error)
	// Registers an address of proxy account to submit / vote external event rather than execute with validator account itself.
	RegisterProxy(context.Context, *MsgRegisterProxy) (*MsgRegisterProxyResponse, error)
	// Clears proxy account info from a validator
	ClearProxy(context.Context, *MsgClearProxy) (*MsgClearProxyResponse, error)
	// Register chain info
	RegisterChain(context.Context, *MsgRegisterChain) (*MsgRegisterChainResponse, error)
	// Unregister chain info
	UnregisterChain(context.Context, *MsgUnregisterChain) (*MsgUnregisterChainResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitEvent(ctx context.Context, req *MsgSubmitEvent) (*MsgSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEvent not implemented")
}
func (*UnimplementedMsgServer) VoteEvent(ctx context.Context, req *MsgVoteEvent) (*MsgVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteEvent not implemented")
}
func (*UnimplementedMsgServer) RegisterProxy(ctx context.Context, req *MsgRegisterProxy) (*MsgRegisterProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProxy not implemented")
}
func (*UnimplementedMsgServer) ClearProxy(ctx context.Context, req *MsgClearProxy) (*MsgClearProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearProxy not implemented")
}
func (*UnimplementedMsgServer) RegisterChain(ctx context.Context, req *MsgRegisterChain) (*MsgRegisterChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChain not implemented")
}
func (*UnimplementedMsgServer) UnregisterChain(ctx context.Context, req *MsgUnregisterChain) (*MsgUnregisterChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterChain not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/SubmitEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEvent(ctx, req.(*MsgSubmitEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_VoteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVoteEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VoteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/VoteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VoteEvent(ctx, req.(*MsgVoteEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterProxy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/RegisterProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterProxy(ctx, req.(*MsgRegisterProxy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClearProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClearProxy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClearProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/ClearProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClearProxy(ctx, req.(*MsgClearProxy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/RegisterChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterChain(ctx, req.(*MsgRegisterChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Msg/UnregisterChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterChain(ctx, req.(*MsgUnregisterChain))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manythings.mitosis.v1beta1.event.server.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvent",
			Handler:    _Msg_SubmitEvent_Handler,
		},
		{
			MethodName: "VoteEvent",
			Handler:    _Msg_VoteEvent_Handler,
		},
		{
			MethodName: "RegisterProxy",
			Handler:    _Msg_RegisterProxy_Handler,
		},
		{
			MethodName: "ClearProxy",
			Handler:    _Msg_ClearProxy_Handler,
		},
		{
			MethodName: "RegisterChain",
			Handler:    _Msg_RegisterChain_Handler,
		},
		{
			MethodName: "UnregisterChain",
			Handler:    _Msg_UnregisterChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mitosis/event/v1beta1/server/server.proto",
}

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries the parameters of the module.
	Params(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Get poll
	Poll(ctx context.Context, in *QueryPoll, opts ...grpc.CallOption) (*QueryPollResponse, error)
	// List polls
	Polls(ctx context.Context, in *QueryPolls, opts ...grpc.CallOption) (*QueryPollsResponse, error)
	// Get proxy
	Proxy(ctx context.Context, in *QueryProxy, opts ...grpc.CallOption) (*QueryProxyResponse, error)
	// Get proxied validator
	ProxyReverse(ctx context.Context, in *QueryProxyReverse, opts ...grpc.CallOption) (*QueryProxyReverseResponse, error)
	// List proxies
	Proxies(ctx context.Context, in *QueryProxies, opts ...grpc.CallOption) (*QueryProxiesResponse, error)
	// Get chain
	Chain(ctx context.Context, in *QueryChain, opts ...grpc.CallOption) (*QueryChainResponse, error)
	// List chain
	Chains(ctx context.Context, in *QueryChains, opts ...grpc.CallOption) (*QueryChainsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParams, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Poll(ctx context.Context, in *QueryPoll, opts ...grpc.CallOption) (*QueryPollResponse, error) {
	out := new(QueryPollResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Poll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Polls(ctx context.Context, in *QueryPolls, opts ...grpc.CallOption) (*QueryPollsResponse, error) {
	out := new(QueryPollsResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Polls", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Proxy(ctx context.Context, in *QueryProxy, opts ...grpc.CallOption) (*QueryProxyResponse, error) {
	out := new(QueryProxyResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Proxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProxyReverse(ctx context.Context, in *QueryProxyReverse, opts ...grpc.CallOption) (*QueryProxyReverseResponse, error) {
	out := new(QueryProxyReverseResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/ProxyReverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Proxies(ctx context.Context, in *QueryProxies, opts ...grpc.CallOption) (*QueryProxiesResponse, error) {
	out := new(QueryProxiesResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Proxies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Chain(ctx context.Context, in *QueryChain, opts ...grpc.CallOption) (*QueryChainResponse, error) {
	out := new(QueryChainResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Chain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Chains(ctx context.Context, in *QueryChains, opts ...grpc.CallOption) (*QueryChainsResponse, error) {
	out := new(QueryChainsResponse)
	err := c.cc.Invoke(ctx, "/manythings.mitosis.v1beta1.event.server.Query/Chains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries the parameters of the module.
	Params(context.Context, *QueryParams) (*QueryParamsResponse, error)
	// Get poll
	Poll(context.Context, *QueryPoll) (*QueryPollResponse, error)
	// List polls
	Polls(context.Context, *QueryPolls) (*QueryPollsResponse, error)
	// Get proxy
	Proxy(context.Context, *QueryProxy) (*QueryProxyResponse, error)
	// Get proxied validator
	ProxyReverse(context.Context, *QueryProxyReverse) (*QueryProxyReverseResponse, error)
	// List proxies
	Proxies(context.Context, *QueryProxies) (*QueryProxiesResponse, error)
	// Get chain
	Chain(context.Context, *QueryChain) (*QueryChainResponse, error)
	// List chain
	Chains(context.Context, *QueryChains) (*QueryChainsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParams) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Poll(ctx context.Context, req *QueryPoll) (*QueryPollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Poll not implemented")
}
func (*UnimplementedQueryServer) Polls(ctx context.Context, req *QueryPolls) (*QueryPollsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Polls not implemented")
}
func (*UnimplementedQueryServer) Proxy(ctx context.Context, req *QueryProxy) (*QueryProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proxy not implemented")
}
func (*UnimplementedQueryServer) ProxyReverse(ctx context.Context, req *QueryProxyReverse) (*QueryProxyReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProxyReverse not implemented")
}
func (*UnimplementedQueryServer) Proxies(ctx context.Context, req *QueryProxies) (*QueryProxiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proxies not implemented")
}
func (*UnimplementedQueryServer) Chain(ctx context.Context, req *QueryChain) (*QueryChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chain not implemented")
}
func (*UnimplementedQueryServer) Chains(ctx context.Context, req *QueryChains) (*QueryChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chains not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPoll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Poll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Poll(ctx, req.(*QueryPoll))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Polls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPolls)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Polls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Polls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Polls(ctx, req.(*QueryPolls))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Proxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProxy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Proxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Proxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Proxy(ctx, req.(*QueryProxy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProxyReverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProxyReverse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProxyReverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/ProxyReverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProxyReverse(ctx, req.(*QueryProxyReverse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Proxies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProxies)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Proxies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Proxies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Proxies(ctx, req.(*QueryProxies))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Chain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Chain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Chain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Chain(ctx, req.(*QueryChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Chains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryChains)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Chains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manythings.mitosis.v1beta1.event.server.Query/Chains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Chains(ctx, req.(*QueryChains))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "manythings.mitosis.v1beta1.event.server.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _Query_Poll_Handler,
		},
		{
			MethodName: "Polls",
			Handler:    _Query_Polls_Handler,
		},
		{
			MethodName: "Proxy",
			Handler:    _Query_Proxy_Handler,
		},
		{
			MethodName: "ProxyReverse",
			Handler:    _Query_ProxyReverse_Handler,
		},
		{
			MethodName: "Proxies",
			Handler:    _Query_Proxies_Handler,
		},
		{
			MethodName: "Chain",
			Handler:    _Query_Chain_Handler,
		},
		{
			MethodName: "Chains",
			Handler:    _Query_Chains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mitosis/event/v1beta1/server/server.proto",
}
